--DROP TABLE IF EXISTS NOTE;
--CREATE TABLE NOTE(ID LONG PRIMARY KEY, TITLE VARCHAR(255),  CREATED_BY VARCHAR(255),  TEXT VARCHAR(5000));
--INSERT INTO NOTE VALUES(1L, 'title1', 'user1', 'text1');
--INSERT INTO NOTE VALUES(2L, 'title2', 'user2', 'text2');

--DROP TABLE IF EXISTS NOTE;
CREATE TABLE NOTE(ID LONG PRIMARY KEY, TITLE VARCHAR(255),  CREATED_BY VARCHAR(255),  TEXT VARCHAR(5000));
--INSERT INTO NOTE VALUES(1, 'title1', 'user1', 'text1'); 
--INSERT INTO NOTE VALUES(2, 'title2', 'user2', 'text2'); 